# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qbites' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qbites
  
#  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

  
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'CountryPickerSwift'
  pod 'Alamofire'
  pod 'SwipeCellKit'
  pod 'ABGaugeViewKit'
  pod "Sheeeeeeeeet"
  pod "SDWebImage"
  pod "LinearProgressBar"
  pod 'SkyFloatingLabelTextField'
  pod 'CropViewController'
  pod 'RLBAlertsPickers'
  pod 'M13Checkbox'
  
end
